global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "txstream"
    static_configs:
      - targets: ["txstream:9090"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: "txstream-worker"
    static_configs:
      - targets: ["host.docker.internal:9091"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s
